{
 "title": "Reserved hotels dashboards",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Rest app", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Users operation",
   "type": "canvas",
   "gridPos": { "h": 2, "w": 18, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Create user",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({application=\"reserved_hotel_rest_service\", __name__=\"create_user_end_total\", code=\"200\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Update user",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({application=\"reserved_hotel_rest_service\", __name__=\"update_user_end_total\", code=\"200\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delete user",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({application=\"reserved_hotel_rest_service\", __name__=\"delete_user_end_total\", code=\"200\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sign in",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count({application=\"reserved_hotel_rest_service\", __name__=\"sign_in_user_end_total\", code=\"200\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hotel operation",
   "type": "canvas",
   "gridPos": { "h": 2, "w": 18, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Create hotel",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({application=\"reserved_hotel_rest_service\", __name__=\"create_hotel_end_total\", code=\"200\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Update hotel",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({application=\"reserved_hotel_rest_service\", __name__=\"update_hotel_end_total\", code=\"200\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delete hotel",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({application=\"reserved_hotel_rest_service\", __name__=\"delete_hotel_end_total\", code=\"200\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All hotels",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum({application=\"reserved_hotel_rest_service\", __name__=\"all_hotels_start_total\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Room operation",
   "type": "canvas",
   "gridPos": { "h": 2, "w": 18, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Create room",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({application=\"reserved_hotel_rest_service\", __name__=\"create_room_end_total\", code=\"200\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Update room",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({application=\"reserved_hotel_rest_service\", __name__=\"update_room_end_total\", code=\"200\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delete room",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({application=\"reserved_hotel_rest_service\", __name__=\"delete_room_end_total\", code=\"200\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Comment operation",
   "type": "canvas",
   "gridPos": { "h": 2, "w": 18, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Create cooment",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({application=\"reserved_hotel_rest_service\", __name__=\"create_comment_end_total\", code=\"200\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Update comment",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({application=\"reserved_hotel_rest_service\", __name__=\"update_comment_end_total\", code=\"200\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delete comment",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({application=\"reserved_hotel_rest_service\", __name__=\"delete_comment_end_total\", code=\"200\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "canvas",
   "gridPos": { "h": 2, "w": 18, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Bad Request",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({application=\"reserved_hotel_rest_service\", __name__=\"create_user_error_total\", code=\"400\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Not Found",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({application=\"reserved_hotel_rest_service\", __name__=\"create_user_error_total\", code=\"404\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "No authorized",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({application=\"reserved_hotel_rest_service\", __name__=\"no_auth_user_error_total\", code=\"401\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Access denied",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({application=\"reserved_hotel_rest_service\", __name__=\"access_denied_error_total\", code=\"403\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}