# Default values for rest-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  #Образ в докере или в другом репозитории
  repository: skydiverkhv/hotel_rest_service

#  Значение	Что делает pullPolicy
#  Always	всегда тянет образ
#  IfNotPresent	только если нет локально
#  Never	не тянет вообще
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 2.0.2

#  service — как обращаться к приложению
#  🧠 Что это значит
#  OpenShift создаст Service
#  Он будет доступен внутри кластера
#
#  📌 type
#  Тип	Значение
#  ClusterIP	только внутри
#  NodePort	через порт ноды
#  LoadBalancer	внешний IP (редко в OpenShift)
#
#  👉 В OpenShift обычно:
#
#  Service = внутри
#  Route = наружу
service:
  type: ClusterIP
  port: 8443

hotel_service:
  db_app_hotel_url: http://hotel-db-app-service.hotel-apps.svc.cluster.local:8081/booking-app
  db_app_auth_url: http://auth-db-app-service.hotel-apps.svc.cluster.local:8084/auth-db-app

redis:
  url: redis-db-service.database.svc.cluster.local
  port: 6379
  time_live_messages: 10m


secret:
  name: rest-app-secret
  giga_chat:
    key: GIGA_CHAT_AUTH_KEY
    value: stub_key
  certificate:
    key_pass: CERTIFICATE_PASSWORD
    key_enabled: CERTIFICATE_ENABLED
    password: "123456"
    enabled: "true"
  spring_security:
    key_value_key: SPRING_SECURITY_KEY
    key_expiration: SPRING_SECURITY_EXPIRATION
    key_level_crypto: SPRING_SECURITY_LEVEL_CRYPTO
    value_key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
    expiration: 600m
    level_crypto: "10"
giga_chat:
  model: "GigaChat-2"
  host: "https://ngw.devices.sberbank.ru:9443/api/v2/oauth"
  create_promt: "https://gigachat.devices.sberbank.ru/api"
  url_promt: "/v1/chat/completions"
  cookie_live: "10m"


resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 256Mi
