apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
data:
  {{ .Values.secret.giga_chat.key }} : {{ .Values.secret.giga_chat.value | b64enc }}
  {{ .Values.secret.certificate.key_pass }} : {{ .Values.secret.certificate.password | b64enc }}
  {{ .Values.secret.certificate.key_enabled }} : {{ .Values.secret.certificate.enabled | b64enc }}
  {{ .Values.secret.spring_security.key_value_key}} : {{ .Values.secret.spring_security.value_key | b64enc }}
  {{ .Values.secret.spring_security.key_expiration }} : {{ .Values.secret.spring_security.expiration | b64enc }}
  {{ .Values.secret.spring_security.key_level_crypto }} : {{ .Values.secret.spring_security.level_crypto | b64enc }}

