name: reserved-hotel-db-service.yml
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Шаг 2: Установка Java
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: 23
          distribution: 'temurin'

      - name: Extract version from pom.xml
        id: version
        run: |
            VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
            echo "PROJECT_VERSION=$VERSION" >> $GITHUB_ENV
            echo "Extracted version: $VERSION"

      # Шаг 3: Сборка и тестирование проекта с помощью Maven
      - name: Build with Maven
        run: mvn -DskipTests clean package


      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/hotel_rest_service:${{ env.PROJECT_VERSION }} .

      - name: Set multiply tags
        run: |
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/hotel_rest_service:${{ env.PROJECT_VERSION }} ${{ secrets.DOCKER_HUB_USERNAME }}/hotel_rest_service:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/hotel_rest_service:${{ env.PROJECT_VERSION }}

      - name: Set tags in gitHub
        run: |
          git config --local user.email "${{ secrets.EMAIL }}"
         git config --local user.name "${{ secrets.USERNAME }}"
          git tag ${{ env.PROJECT_VERSION }}
          git push origin ${{ env.PROJECT_VERSION }}